# Exploración inicial de datos

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow as pa

In [2]:
BASE_DIR = Path().resolve().parents[1]  # sube dos niveles
DATA_DIR = BASE_DIR / "data" / "01_raw"
file_path = DATA_DIR / "covid_raw.csv"

# Leer el archivo CSV
coviddailiy_df = pd.read_csv(file_path)

In [3]:
display(coviddailiy_df.head())

,date_of_interest,CASE_COUNT,PROBABLE_CASE_COUNT,HOSPITALIZED_COUNT,DEATH_COUNT,CASE_COUNT_7DAY_AVG,ALL_CASE_COUNT_7DAY_AVG,HOSP_COUNT_7DAY_AVG,DEATH_COUNT_7DAY_AVG,BX_CASE_COUNT,...,SI_CASE_COUNT,SI_PROBABLE_CASE_COUNT,SI_HOSPITALIZED_COUNT,SI_DEATH_COUNT,SI_PROBABLE_CASE_COUNT_7DAY_AVG,SI_CASE_COUNT_7DAY_AVG,SI_ALL_CASE_COUNT_7DAY_AVG,SI_HOSPITALIZED_COUNT_7DAY_AVG,SI_DEATH_COUNT_7DAY_AVG,INCOMPLETE
0,02/29/2020,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,03/01/2020,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,03/02/2020,0,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,03/03/2020,1,0,8,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,03/04/2020,5,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
coviddailiy_df.sample(10)

,date_of_interest,CASE_COUNT,PROBABLE_CASE_COUNT,HOSPITALIZED_COUNT,DEATH_COUNT,CASE_COUNT_7DAY_AVG,ALL_CASE_COUNT_7DAY_AVG,HOSP_COUNT_7DAY_AVG,DEATH_COUNT_7DAY_AVG,BX_CASE_COUNT,...,SI_CASE_COUNT,SI_PROBABLE_CASE_COUNT,SI_HOSPITALIZED_COUNT,SI_DEATH_COUNT,SI_PROBABLE_CASE_COUNT_7DAY_AVG,SI_CASE_COUNT_7DAY_AVG,SI_ALL_CASE_COUNT_7DAY_AVG,SI_HOSPITALIZED_COUNT_7DAY_AVG,SI_DEATH_COUNT_7DAY_AVG,INCOMPLETE
1880,04/23/2025,250,140,26,2,232,381,30,2,56,...,7,8,1,2,9,12,21,1,0,0
1064,01/28/2023,841,301,107,15,1438,1862,116,20,151,...,71,28,11,0,45,101,146,10,1,0
1719,11/13/2024,101,41,12,1,93,135,15,1,10,...,8,2,0,0,4,8,12,1,0,0
121,06/29/2020,437,26,47,19,317,333,42,17,75,...,23,1,1,3,1,17,18,2,1,0
1906,05/19/2025,161,114,10,0,134,215,15,1,26,...,9,5,0,0,4,8,11,1,0,0
980,11/05/2022,1400,465,129,17,2037,2630,144,14,224,...,65,26,7,1,44,106,150,9,1,0
1328,10/19/2023,479,264,59,2,444,667,53,4,75,...,37,29,3,0,22,31,53,3,0,0
701,01/30/2022,1426,225,143,87,3324,3680,248,99,138,...,116,14,17,4,19,229,248,19,7,0
849,06/27/2022,3796,898,133,13,2950,3590,127,12,505,...,263,47,11,1,36,187,223,8,1,0
1872,04/15/2025,297,172,45,1,259,426,34,1,66,...,16,22,5,0,14,15,29,2,0,0

In [5]:
coviddailiy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1915 entries, 0 to 1914
Data columns (total 55 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   date_of_interest                 1915 non-null   object
 1   CASE_COUNT                       1915 non-null   int64
 2   PROBABLE_CASE_COUNT              1915 non-null   int64
 3   HOSPITALIZED_COUNT               1915 non-null   int64
 4   DEATH_COUNT                      1915 non-null   int64
 5   CASE_COUNT_7DAY_AVG              1915 non-null   int64
 6   ALL_CASE_COUNT_7DAY_AVG          1915 non-null   int64
 7   HOSP_COUNT_7DAY_AVG              1915 non-null   int64
 8   DEATH_COUNT_7DAY_AVG             1915 non-null   int64
 9   BX_CASE_COUNT                    1915 non-null   int64
 10  BX_PROBABLE_CASE_COUNT           1915 non-null   int64
 11  BX_HOSPITALIZED_COUNT            1915 non-null   int64
 12  BX_DEATH_COUNT                   1915 non-null   int64
 13  BX_CASE_COUNT_7DAY_AVG           1915 non-null   int64
 14  BX_PROBABLE_CASE_COUNT_7DAY_AVG  1915 non-null   int64
 15  BX_ALL_CASE_COUNT_7DAY_AVG       1915 non-null   int64
 16  BX_HOSPITALIZED_COUNT_7DAY_AVG   1915 non-null   int64
 17  BX_DEATH_COUNT_7DAY_AVG          1915 non-null   int64
 18  BK_CASE_COUNT                    1915 non-null   int64
 19  BK_PROBABLE_CASE_COUNT           1915 non-null   int64
 20  BK_HOSPITALIZED_COUNT            1915 non-null   int64
 21  BK_DEATH_COUNT                   1915 non-null   int64
 22  BK_CASE_COUNT_7DAY_AVG           1915 non-null   int64
 23  BK_PROBABLE_CASE_COUNT_7DAY_AVG  1915 non-null   int64
 24  BK_ALL_CASE_COUNT_7DAY_AVG       1915 non-null   int64
 25  BK_HOSPITALIZED_COUNT_7DAY_AVG   1915 non-null   int64
 26  BK_DEATH_COUNT_7DAY_AVG          1915 non-null   int64
 27  MN_CASE_COUNT                    1915 non-null   int64
 28  MN_PROBABLE_CASE_COUNT           1915 non-null   int64
 29  MN_HOSPITALIZED_COUNT            1915 non-null   int64
 30  MN_DEATH_COUNT                   1915 non-null   int64
 31  MN_CASE_COUNT_7DAY_AVG           1915 non-null   int64
 32  MN_PROBABLE_CASE_COUNT_7DAY_AVG  1915 non-null   int64
 33  MN_ALL_CASE_COUNT_7DAY_AVG       1915 non-null   int64
 34  MN_HOSPITALIZED_COUNT_7DAY_AVG   1915 non-null   int64
 35  MN_DEATH_COUNT_7DAY_AVG          1915 non-null   int64
 36  QN_CASE_COUNT                    1915 non-null   int64
 37  QN_PROBABLE_CASE_COUNT           1915 non-null   int64
 38  QN_HOSPITALIZED_COUNT            1915 non-null   int64
 39  QN_DEATH_COUNT                   1915 non-null   int64
 40  QN_CASE_COUNT_7DAY_AVG           1915 non-null   int64
 41  QN_PROBABLE_CASE_COUNT_7DAY_AVG  1915 non-null   int64
 42  QN_ALL_CASE_COUNT_7DAY_AVG       1915 non-null   int64
 43  QN_HOSPITALIZED_COUNT_7DAY_AVG   1915 non-null   int64
 44  QN_DEATH_COUNT_7DAY_AVG          1915 non-null   int64
 45  SI_CASE_COUNT                    1915 non-null   int64
 46  SI_PROBABLE_CASE_COUNT           1915 non-null   int64
 47  SI_HOSPITALIZED_COUNT            1915 non-null   int64
 48  SI_DEATH_COUNT                   1915 non-null   int64
 49  SI_PROBABLE_CASE_COUNT_7DAY_AVG  1915 non-null   int64
 50  SI_CASE_COUNT_7DAY_AVG           1915 non-null   int64
 51  SI_ALL_CASE_COUNT_7DAY_AVG       1915 non-null   int64
 52  SI_HOSPITALIZED_COUNT_7DAY_AVG   1915 non-null   int64
 53  SI_DEATH_COUNT_7DAY_AVG          1915 non-null   int64
 54  INCOMPLETE                       1915 non-null   int64
dtypes: int64(54), object(1)
memory usage: 823.0+ KB

In [6]:
missing_values = ["", " ", "NA", "N/A"]
coviddailiy_df = coviddailiy_df.replace(missing_values, np.nan)

In [7]:
MISSING_THRESHOLD = 0.8
missing_percentage = coviddailiy_df.isnull().sum() / len(coviddailiy_df)
columns_to_remove_missing = missing_percentage[
    missing_percentage > MISSING_THRESHOLD
].index.tolist()
print(" Columnas eliminadas por tener más del 80% de valores faltantes:", columns_to_remove_missing)
coviddailiy_df = coviddailiy_df.drop(columns=columns_to_remove_missing)

 Columnas eliminadas por tener más del 80% de valores faltantes: []

In [8]:
columns_to_remove_irrelevant = ["INCOMPLETE"]
print(" Columnas eliminadas por ser irrelevantes:", columns_to_remove_irrelevant)
for column in columns_to_remove_irrelevant:
    print(
        f"{column}: Esta columna no aporta información relevante para el análisis, "
        "esta información fue tomada del diccionario de datos del dataset."
    )
coviddailiy_df = coviddailiy_df.drop(columns=columns_to_remove_irrelevant)

 Columnas eliminadas por ser irrelevantes: ['INCOMPLETE']
INCOMPLETE: Esta columna no aporta información relevante para el análisis, esta información fue tomada del diccionario de datos del dataset.

In [9]:
print(coviddailiy_df.columns.tolist())

['date_of_interest', 'CASE_COUNT', 'PROBABLE_CASE_COUNT', 'HOSPITALIZED_COUNT', 'DEATH_COUNT', 'CASE_COUNT_7DAY_AVG', 'ALL_CASE_COUNT_7DAY_AVG', 'HOSP_COUNT_7DAY_AVG', 'DEATH_COUNT_7DAY_AVG', 'BX_CASE_COUNT', 'BX_PROBABLE_CASE_COUNT', 'BX_HOSPITALIZED_COUNT', 'BX_DEATH_COUNT', 'BX_CASE_COUNT_7DAY_AVG', 'BX_PROBABLE_CASE_COUNT_7DAY_AVG', 'BX_ALL_CASE_COUNT_7DAY_AVG', 'BX_HOSPITALIZED_COUNT_7DAY_AVG', 'BX_DEATH_COUNT_7DAY_AVG', 'BK_CASE_COUNT', 'BK_PROBABLE_CASE_COUNT', 'BK_HOSPITALIZED_COUNT', 'BK_DEATH_COUNT', 'BK_CASE_COUNT_7DAY_AVG', 'BK_PROBABLE_CASE_COUNT_7DAY_AVG', 'BK_ALL_CASE_COUNT_7DAY_AVG', 'BK_HOSPITALIZED_COUNT_7DAY_AVG', 'BK_DEATH_COUNT_7DAY_AVG', 'MN_CASE_COUNT', 'MN_PROBABLE_CASE_COUNT', 'MN_HOSPITALIZED_COUNT', 'MN_DEATH_COUNT', 'MN_CASE_COUNT_7DAY_AVG', 'MN_PROBABLE_CASE_COUNT_7DAY_AVG', 'MN_ALL_CASE_COUNT_7DAY_AVG', 'MN_HOSPITALIZED_COUNT_7DAY_AVG', 'MN_DEATH_COUNT_7DAY_AVG', 'QN_CASE_COUNT', 'QN_PROBABLE_CASE_COUNT', 'QN_HOSPITALIZED_COUNT', 'QN_DEATH_COUNT', 'QN_CASE_COUNT_7DAY_AVG', 'QN_PROBABLE_CASE_COUNT_7DAY_AVG', 'QN_ALL_CASE_COUNT_7DAY_AVG', 'QN_HOSPITALIZED_COUNT_7DAY_AVG', 'QN_DEATH_COUNT_7DAY_AVG', 'SI_CASE_COUNT', 'SI_PROBABLE_CASE_COUNT', 'SI_HOSPITALIZED_COUNT', 'SI_DEATH_COUNT', 'SI_PROBABLE_CASE_COUNT_7DAY_AVG', 'SI_CASE_COUNT_7DAY_AVG', 'SI_ALL_CASE_COUNT_7DAY_AVG', 'SI_HOSPITALIZED_COUNT_7DAY_AVG', 'SI_DEATH_COUNT_7DAY_AVG']

In [10]:
coviddailiy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1915 entries, 0 to 1914
Data columns (total 54 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   date_of_interest                 1915 non-null   object
 1   CASE_COUNT                       1915 non-null   int64
 2   PROBABLE_CASE_COUNT              1915 non-null   int64
 3   HOSPITALIZED_COUNT               1915 non-null   int64
 4   DEATH_COUNT                      1915 non-null   int64
 5   CASE_COUNT_7DAY_AVG              1915 non-null   int64
 6   ALL_CASE_COUNT_7DAY_AVG          1915 non-null   int64
 7   HOSP_COUNT_7DAY_AVG              1915 non-null   int64
 8   DEATH_COUNT_7DAY_AVG             1915 non-null   int64
 9   BX_CASE_COUNT                    1915 non-null   int64
 10  BX_PROBABLE_CASE_COUNT           1915 non-null   int64
 11  BX_HOSPITALIZED_COUNT            1915 non-null   int64
 12  BX_DEATH_COUNT                   1915 non-null   int64
 13  BX_CASE_COUNT_7DAY_AVG           1915 non-null   int64
 14  BX_PROBABLE_CASE_COUNT_7DAY_AVG  1915 non-null   int64
 15  BX_ALL_CASE_COUNT_7DAY_AVG       1915 non-null   int64
 16  BX_HOSPITALIZED_COUNT_7DAY_AVG   1915 non-null   int64
 17  BX_DEATH_COUNT_7DAY_AVG          1915 non-null   int64
 18  BK_CASE_COUNT                    1915 non-null   int64
 19  BK_PROBABLE_CASE_COUNT           1915 non-null   int64
 20  BK_HOSPITALIZED_COUNT            1915 non-null   int64
 21  BK_DEATH_COUNT                   1915 non-null   int64
 22  BK_CASE_COUNT_7DAY_AVG           1915 non-null   int64
 23  BK_PROBABLE_CASE_COUNT_7DAY_AVG  1915 non-null   int64
 24  BK_ALL_CASE_COUNT_7DAY_AVG       1915 non-null   int64
 25  BK_HOSPITALIZED_COUNT_7DAY_AVG   1915 non-null   int64
 26  BK_DEATH_COUNT_7DAY_AVG          1915 non-null   int64
 27  MN_CASE_COUNT                    1915 non-null   int64
 28  MN_PROBABLE_CASE_COUNT           1915 non-null   int64
 29  MN_HOSPITALIZED_COUNT            1915 non-null   int64
 30  MN_DEATH_COUNT                   1915 non-null   int64
 31  MN_CASE_COUNT_7DAY_AVG           1915 non-null   int64
 32  MN_PROBABLE_CASE_COUNT_7DAY_AVG  1915 non-null   int64
 33  MN_ALL_CASE_COUNT_7DAY_AVG       1915 non-null   int64
 34  MN_HOSPITALIZED_COUNT_7DAY_AVG   1915 non-null   int64
 35  MN_DEATH_COUNT_7DAY_AVG          1915 non-null   int64
 36  QN_CASE_COUNT                    1915 non-null   int64
 37  QN_PROBABLE_CASE_COUNT           1915 non-null   int64
 38  QN_HOSPITALIZED_COUNT            1915 non-null   int64
 39  QN_DEATH_COUNT                   1915 non-null   int64
 40  QN_CASE_COUNT_7DAY_AVG           1915 non-null   int64
 41  QN_PROBABLE_CASE_COUNT_7DAY_AVG  1915 non-null   int64
 42  QN_ALL_CASE_COUNT_7DAY_AVG       1915 non-null   int64
 43  QN_HOSPITALIZED_COUNT_7DAY_AVG   1915 non-null   int64
 44  QN_DEATH_COUNT_7DAY_AVG          1915 non-null   int64
 45  SI_CASE_COUNT                    1915 non-null   int64
 46  SI_PROBABLE_CASE_COUNT           1915 non-null   int64
 47  SI_HOSPITALIZED_COUNT            1915 non-null   int64
 48  SI_DEATH_COUNT                   1915 non-null   int64
 49  SI_PROBABLE_CASE_COUNT_7DAY_AVG  1915 non-null   int64
 50  SI_CASE_COUNT_7DAY_AVG           1915 non-null   int64
 51  SI_ALL_CASE_COUNT_7DAY_AVG       1915 non-null   int64
 52  SI_HOSPITALIZED_COUNT_7DAY_AVG   1915 non-null   int64
 53  SI_DEATH_COUNT_7DAY_AVG          1915 non-null   int64
dtypes: int64(53), object(1)
memory usage: 808.0+ KB

## 📊 Clasificación de Variables del Dataset COVID-19

### 📅 **Variables Datetime**
- `date_of_interest`

### 🔢 **Variables Numéricas Discretas**

- `CASE_COUNT`                   
- `PROBABLE_CASE_COUNT`          
- `HOSPITALIZED_COUNT`           
- `DEATH_COUNT`                  
- `BX_CASE_COUNT`                
- `BX_PROBABLE_CASE_COUNT`       
- `BX_HOSPITALIZED_COUNT`        
- `BX_DEATH_COUNT`               
- `BK_CASE_COUNT`                
- `BK_PROBABLE_CASE_COUNT`       
- `BK_HOSPITALIZED_COUNT`        
- `BK_DEATH_COUNT`               
- `MN_CASE_COUNT`                
- `MN_PROBABLE_CASE_COUNT`       
- `MN_HOSPITALIZED_COUNT`        
- `MN_DEATH_COUNT`               
- `QN_CASE_COUNT`                
- `QN_PROBABLE_CASE_COUNT`       
- `QN_HOSPITALIZED_COUNT`       
- `QN_DEATH_COUNT`               
- `SI_CASE_COUNT`                
- `SI_PROBABLE_CASE_COUNT`       
- `SI_HOSPITALIZED_COUNT`        
- `SI_DEATH_COUNT`   

### 📈 **Variables Numéricas Continuas**

- `CASE_COUNT_7DAY_AVG`                    
- `ALL_CASE_COUNT_7DAY_AVG`                
- `HOSP_COUNT_7DAY_AVG`                    
- `DEATH_COUNT_7DAY_AVG`                   
- `BX_CASE_COUNT_7DAY_AVG`                 
- `BX_PROBABLE_CASE_COUNT_7DAY_AVG`        
- `BX_ALL_CASE_COUNT_7DAY_AVG`             
- `BX_HOSPITALIZED_COUNT_7DAY_AVG`         
- `BX_DEATH_COUNT_7DAY_AVG`                
- `BK_CASE_COUNT_7DAY_AVG`                 
- `BK_PROBABLE_CASE_COUNT_7DAY_AVG`        
- `BK_ALL_CASE_COUNT_7DAY_AVG`             
- `BK_HOSPITALIZED_COUNT_7DAY_AVG`         
- `BK_DEATH_COUNT_7DAY_AVG`                
- `MN_CASE_COUNT_7DAY_AVG`                 
- `MN_PROBABLE_CASE_COUNT_7DAY_AVG`        
- `MN_ALL_CASE_COUNT_7DAY_AVG`             
- `MN_HOSPITALIZED_COUNT_7DAY_AVG`         
- `MN_DEATH_COUNT_7DAY_AVG`                
- `QN_CASE_COUNT_7DAY_AVG`                
- `QN_PROBABLE_CASE_COUNT_7DAY_AVG`       
- `QN_ALL_CASE_COUNT_7DAY_AVG`             
- `QN_HOSPITALIZED_COUNT_7DAY_AVG`         
- `QN_DEATH_COUNT_7DAY_AVG`                
- `SI_CASE_COUNT_7DAY_AVG`                 
- `SI_PROBABLE_CASE_COUNT_7DAY_AVG`        
- `SI_ALL_CASE_COUNT_7DAY_AVG`             
- `SI_HOSPITALIZED_COUNT_7DAY_AVG`         
- `SI_DEATH_COUNT_7DAY_AVG`

In [11]:
coviddailiy_df["date_of_interest"] = pd.to_datetime(coviddailiy_df["date_of_interest"])

In [12]:
coviddailiy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1915 entries, 0 to 1914
Data columns (total 54 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   date_of_interest                 1915 non-null   datetime64[ns]
 1   CASE_COUNT                       1915 non-null   int64
 2   PROBABLE_CASE_COUNT              1915 non-null   int64
 3   HOSPITALIZED_COUNT               1915 non-null   int64
 4   DEATH_COUNT                      1915 non-null   int64
 5   CASE_COUNT_7DAY_AVG              1915 non-null   int64
 6   ALL_CASE_COUNT_7DAY_AVG          1915 non-null   int64
 7   HOSP_COUNT_7DAY_AVG              1915 non-null   int64
 8   DEATH_COUNT_7DAY_AVG             1915 non-null   int64
 9   BX_CASE_COUNT                    1915 non-null   int64
 10  BX_PROBABLE_CASE_COUNT           1915 non-null   int64
 11  BX_HOSPITALIZED_COUNT            1915 non-null   int64
 12  BX_DEATH_COUNT                   1915 non-null   int64
 13  BX_CASE_COUNT_7DAY_AVG           1915 non-null   int64
 14  BX_PROBABLE_CASE_COUNT_7DAY_AVG  1915 non-null   int64
 15  BX_ALL_CASE_COUNT_7DAY_AVG       1915 non-null   int64
 16  BX_HOSPITALIZED_COUNT_7DAY_AVG   1915 non-null   int64
 17  BX_DEATH_COUNT_7DAY_AVG          1915 non-null   int64
 18  BK_CASE_COUNT                    1915 non-null   int64
 19  BK_PROBABLE_CASE_COUNT           1915 non-null   int64
 20  BK_HOSPITALIZED_COUNT            1915 non-null   int64
 21  BK_DEATH_COUNT                   1915 non-null   int64
 22  BK_CASE_COUNT_7DAY_AVG           1915 non-null   int64
 23  BK_PROBABLE_CASE_COUNT_7DAY_AVG  1915 non-null   int64
 24  BK_ALL_CASE_COUNT_7DAY_AVG       1915 non-null   int64
 25  BK_HOSPITALIZED_COUNT_7DAY_AVG   1915 non-null   int64
 26  BK_DEATH_COUNT_7DAY_AVG          1915 non-null   int64
 27  MN_CASE_COUNT                    1915 non-null   int64
 28  MN_PROBABLE_CASE_COUNT           1915 non-null   int64
 29  MN_HOSPITALIZED_COUNT            1915 non-null   int64
 30  MN_DEATH_COUNT                   1915 non-null   int64
 31  MN_CASE_COUNT_7DAY_AVG           1915 non-null   int64
 32  MN_PROBABLE_CASE_COUNT_7DAY_AVG  1915 non-null   int64
 33  MN_ALL_CASE_COUNT_7DAY_AVG       1915 non-null   int64
 34  MN_HOSPITALIZED_COUNT_7DAY_AVG   1915 non-null   int64
 35  MN_DEATH_COUNT_7DAY_AVG          1915 non-null   int64
 36  QN_CASE_COUNT                    1915 non-null   int64
 37  QN_PROBABLE_CASE_COUNT           1915 non-null   int64
 38  QN_HOSPITALIZED_COUNT            1915 non-null   int64
 39  QN_DEATH_COUNT                   1915 non-null   int64
 40  QN_CASE_COUNT_7DAY_AVG           1915 non-null   int64
 41  QN_PROBABLE_CASE_COUNT_7DAY_AVG  1915 non-null   int64
 42  QN_ALL_CASE_COUNT_7DAY_AVG       1915 non-null   int64
 43  QN_HOSPITALIZED_COUNT_7DAY_AVG   1915 non-null   int64
 44  QN_DEATH_COUNT_7DAY_AVG          1915 non-null   int64
 45  SI_CASE_COUNT                    1915 non-null   int64
 46  SI_PROBABLE_CASE_COUNT           1915 non-null   int64
 47  SI_HOSPITALIZED_COUNT            1915 non-null   int64
 48  SI_DEATH_COUNT                   1915 non-null   int64
 49  SI_PROBABLE_CASE_COUNT_7DAY_AVG  1915 non-null   int64
 50  SI_CASE_COUNT_7DAY_AVG           1915 non-null   int64
 51  SI_ALL_CASE_COUNT_7DAY_AVG       1915 non-null   int64
 52  SI_HOSPITALIZED_COUNT_7DAY_AVG   1915 non-null   int64
 53  SI_DEATH_COUNT_7DAY_AVG          1915 non-null   int64
dtypes: datetime64[ns](1), int64(53)
memory usage: 808.0 KB

In [13]:
coviddailiy_df.sample(10)

,date_of_interest,CASE_COUNT,PROBABLE_CASE_COUNT,HOSPITALIZED_COUNT,DEATH_COUNT,CASE_COUNT_7DAY_AVG,ALL_CASE_COUNT_7DAY_AVG,HOSP_COUNT_7DAY_AVG,DEATH_COUNT_7DAY_AVG,BX_CASE_COUNT,...,QN_DEATH_COUNT_7DAY_AVG,SI_CASE_COUNT,SI_PROBABLE_CASE_COUNT,SI_HOSPITALIZED_COUNT,SI_DEATH_COUNT,SI_PROBABLE_CASE_COUNT_7DAY_AVG,SI_CASE_COUNT_7DAY_AVG,SI_ALL_CASE_COUNT_7DAY_AVG,SI_HOSPITALIZED_COUNT_7DAY_AVG,SI_DEATH_COUNT_7DAY_AVG
1331,2023-10-22,257,156,41,1,436,651,53,3,55,...,2,17,15,1,0,21,30,52,3,0
201,2020-09-17,441,35,34,3,364,398,29,5,61,...,2,25,0,2,0,1,19,20,1,0
1356,2023-11-16,428,231,47,1,355,593,37,3,72,...,1,33,13,7,0,25,34,58,4,0
443,2021-05-17,453,132,72,16,463,608,61,20,79,...,6,37,16,5,0,14,43,57,4,1
1907,2025-05-20,170,92,16,1,135,216,16,1,34,...,0,6,3,1,0,3,7,11,1,0
779,2022-04-18,2350,449,59,3,1981,2351,49,5,187,...,1,167,29,4,1,17,125,142,4,0
1489,2024-03-28,164,66,25,0,147,224,21,2,32,...,0,9,6,1,0,9,10,19,1,0
1374,2023-12-04,789,468,70,2,567,918,59,3,165,...,1,46,62,5,0,36,42,78,5,0
416,2021-04-20,1606,487,155,35,1700,2255,182,38,286,...,10,146,34,11,2,43,161,203,14,2
241,2020-10-27,742,231,46,9,600,780,51,6,119,...,1,76,27,3,0,21,55,75,4,0

In [14]:
schema = pa.Table.from_pandas(coviddailiy_df).schema

In [15]:
BASE_DIR = Path().resolve().parents[1]
INTERMEDIATE_DIR = BASE_DIR / "data" / "02_intermediate"
INTERMEDIATE_DIR.mkdir(parents=True, exist_ok=True)
coviddailiy_df.to_parquet(INTERMEDIATE_DIR / "covid_type_fixed.parquet", index=False, schema=schema)
print(
    "Archivo guardado en formato parquet en:",
    (INTERMEDIATE_DIR / "covid_type_fixed.parquet").resolve(),
)

Archivo guardado en formato parquet en: /workspaces/MTA-NYCTrains/data/02_intermediate/covid_type_fixed.parquet